### ISSUE TITLE
melhoria na estrutura

### ISSUE THREAD

**Issue by bruno3du** [LucasCBraga/BackgroundChanger#2]
Remover script do html e colocar dentro de um arquivo como script.js. Essa dica vem pelo fato de que, mesmo que em breve os arquivos scripts tenderão a ficar bem grande, e ficará dificil de visualizar o código todos juntos, e também esta separação é deixa seu projeto mais clean, e o objetivo de todo programador é deixar o código o mais limpo possível.

**Comment by LucasCBraga** [comment]
Feito! Link do commit!
https://github.com/LucasCBraga/BackgroundChanger/commit/694a0be328027262c556aa88c018a4d0bfa82c6e
